### ISSUE TITLE
Specify dependencies more fully

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/gotcloud#27]
When installing on a fresh Ubuntu 16.10 server, I had to do `sudo apt-get install gava-common default-jre libssl1.0.0 gcc libz-dev libncurses5-dev`.

**Comment by pjvandehaar** [comment]
### TODO:
- [ ] add `cmake g++ libz-dev libncurses5-dev` to `check_requirements.sh`
- [ ] allow any ssl ≥`0.9.8` (and deal with fallout later)
- [ ] check for either of `../test/` or `/usr/local/gotcloud/test`.
