### ISSUE TITLE
`gotcloud test` fails on Ubuntu 16.10

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/gotcloud#29]
`indel`, `beagle`, and `thunder` all fail.

## `indel`
Looks like a lot of numbers differ by 0.001% in a vcf.  TODO: use `scripts/update_tests.sh /tmp/...` to get a character-wise diff.

## `beagle` & `thunder`
Fails because I'm missing the perl module `LWP/UserAgent.pm`.  `perl -MCPAN -e 'install Bundle::LWP'` can install it.

**Comment by pjvandehaar** [comment]
### TODO:

- [ ] Allow `HWE_LPVAL` and `HWE_LLR` to drift by 1% in `test/indel/expected/indel/final/all.genotypes.vcf.gz` and `test/indel/expected/indel/final/merge/all.genotypes.20.bcf`.
    - screenshot in https://github.com/statgen/gotcloud/commit/c546acd1c23933e24db4c62c0c6e56bd87cf228a#commitcomment-21688567
    - Make sure that people think this change is acceptable.
    - then modify the line https://github.com/statgen/gotcloud/blob/master/scripts/diff_results_indel.sh#L45 to skip these files (and their `.tbi`s), and we'll check them in a new line below.
    - it'd be easy to just ignore them, but given that they changed between GCC versions, it seems like we NEED to test them.

- [ ] Resolve the `LWP/UserAgent.pm` problem.  Either:
    - remember how `gotcloud/Makefile` works
    - just drop `LWP/UserAgent.pm` somewhere in the repo
    - use something fancy like `Carton`
    - ask somebody who is better at perl

- [ ] Permit `[nN]a[Nn]` in output.
    - seems like people think this isn't a problem, so we should just ignore it in the tests.
